config/routes.rb
Rails.application.routes.default_url_options[:host] = "http://localhost:3000/"
Rails.application.routes.draw do
  devise_for :users
  resources :users#, only: [:show]
  post '/update_profile' => 'users#update_profile'

  resources :room_messages
  resources :rooms

  root controller: :rooms, action: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
                         inverse_of: :room
  has_and_belongs_to_many :users
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  attr_accessor :avatar_url
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  # merge profile pic to json representation of the RoomMessage model
  def as_json(options)
    h = super(options).merge(username: user.username)
    h[:avatar_url] = Rails.application.routes.url_helpers.rails_blob_path(user.avatar)
    h
  end

  def created_at
    attributes['created_at'].strftime("%d %B, %l:%M%P")
  end

  def updated_at
    attributes['updated_at'].strftime("%d %B, %l:%M%P")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rooms
  has_many :messages
  has_one_attached :avatar
  has_many :room_messages, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  before_create :add_default_avatar

  #def user_avatar(user_id)
   #user = User.find(user_id)
  # if user.avatar.attached?
  #    user.avatar
  # else
  #     self.avatar.attach(io: File.open(Rails.root.join("app", "assets", "images", "default-profile.png")), filename: 'default-profile.png' , content_type: "image/png")
  # end
#  end


  def add_default_avatar
   unless avatar.attached?
     self.avatar.attach(io: File.open(Rails.root.join("app", "assets", "images", "default-profile.png")), filename: 'default-profile.png' , content_type: "image/png")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :first_name, :last_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :avatar])
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
   before_action :load_entities

  def create
    
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)
    
    RoomChannel.broadcast_to @room, @room_message
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end

  
end

# 5. here we broadcast room message to room stream after creating it
# we added the line RoomChannel.broadcast_to @room, @room_message which will broadcast to the room’s specific stream the @room_message transformed to json via the to_json method.

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # the before action loads all the rooms @rooms and @room when applicable
  before_action :load_entities
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def destroy
    @room.delete
    flash[:success] = "Room was successfully deleted"
    redirect_back fallback_location: root_path
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def create
    user = User.create!(user_params)
    session[:user_id] = user.id
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email_address, :password, :avatar)
    end
end

app/controllers/user_controller.rb
class UsersController < ApplicationRecord

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:bio)
  end

  def index
  end

  def update_profile
    current_user.update(bio: user_params[:bio])
    redirect_to user_path(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def renderImage(imageUrl)
    "<img src='#{imageUrl}'>"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>


    <title>Chitchat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- EmojiOneArea CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.css">
  <title>ChitChat</title>
  </head>

  <body>
  <% unless action_name == "new" %>
    <nav class="navbar navbar-light" style="background-color: #e98888b8;">

        <%= link_to root_path, :action => 'go' do %>
          <div>
          <img src="https://i.imgur.com/oWcqCmw.png" width="140" height="70" class="d-inline-block align-top" alt="">
          </div>
        <% end %>
      <span class="navbar-text">
        <% if current_user %>
          <ul class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
              <% user_pic = image_tag current_user.avatar, size: 30, class: "avatar" %>
            <% else %>
              <% user_pic = image_tag "default-profile.png", size: 30, class: "avatar" %>
            <% end %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

              Logged in as <%= current_user.email %> <%=user_pic%>

              <% if current_user.avatar.attached? %>
                <% user_pic = image_tag current_user.avatar, size: 30, class: "avatar" %>
              <% else %>
                <% user_pic = image_tag "default-profile.png", size: 30 %>
              <% end %>

            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" <%= link_to 'Profile page', user_path(current_user) %></a>
              <a class="dropdown-item" <%= link_to 'Edit Account', edit_user_registration_path %></a>
              <a class="dropdown-item" <%= link_to 'Logout', destroy_user_session_path, method: :delete %></a>
            </div>
          </ul>
        <% else %>
          <%# link_to "Log In", login_path %> or
          <%# link_to "Sign Up", signup_path %>
        <% end %>
      </span>
    </nav>
  <% end %>

    <div class="container">
    <%= yield %>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.js"></script>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @room do |form| %>
  <%= form.text_field :name, placeholder: "please, keep it clean" %>
  <%= form.submit "Create room", class: 'btn btn-primary' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div>
  <%= link_to 'Create a room', new_room_path %>

</div>

<% if @rooms.present? %>
  <nav class="nav">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="">
    There are no rooms
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="container">
<br>
<p><%= notice %></p>
<div class="typewriter-heading-div">

  <h1 class="typewriter text-left">Hey <%= current_user.first_name %>, come to chat?</h1>
</div>  

<br>
<div class="container">
  <h1 class="signup bolder">Open rooms</h1>
<br>
    <%if @rooms.present? %>
        <% @rooms.each do |room| %>
          <%= link_to room.name, room_path(room), class: "btn btn-outline-secondary btn-lg btn-block" %>
          <%= link_to 'Delete', room_path(room), method: :delete, data: { confirm: 'Are you sure?' } %>

        <% end %>
    <% else %>
      <br>
      <br>
      <p class="tagline">There are currently no active rooms</p>
    <% end %>
    <br>
    <br>
    <p class="tagline">Don't fancy any of those?</p>
    <div class= "tagline">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        Create a new room
      <% end %>
</div>
</div>
</div>

app/views/rooms/new.html.erb
<nav class="navbar navbar-light" style="background-color: #e98888b8;">

        <%= link_to root_path, :action => 'go' do %>
          <div>
          <img src="https://i.imgur.com/oWcqCmw.png" width="140" height="70" class="d-inline-block align-top" alt="">
          </div>
        <% end %>
      <span class="navbar-text">
        <% if current_user %>
          <ul class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
              <% user_pic = image_tag current_user.avatar, size: 30, class: "avatar" %>
            <% else %>
              <% user_pic = image_tag "default-profile.png", size: 30, class: "avatar" %>
            <% end %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Logged in as <%= current_user.email %> <%=user_pic%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" <%= link_to 'Profile page', user_path(current_user) %></a>
              <a class="dropdown-item" <%= link_to 'Edit Account', edit_user_registration_path %></a>
              <a class="dropdown-item" <%= link_to 'Logout', destroy_user_session_path, method: :delete %></a>
            </div>
          </ul>

        <% else %>
          <%# link_to "Log In", login_path %> or
          <%# link_to "Sign Up", signup_path %>
        <% end %>
      </span>
    </nav>
  <br>
<div class="center-text">
  <h1 class="typewriter">What would you like to chat about?</h1>
</div>

<br>
  <div class="new-chat-form">
    <img src="https://i.imgur.com/mDeCSid.png" width="300" height="150" >
    <%= render partial: 'form' %>
  <div>

app/views/rooms/show.html.erb
<br>
<div class="typewriter-heading-div">
<h1 class="typewriter"> <%= @room.name %> </h1>
</div>
<br>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">


          <!--current user messages-->
           

            <!--all other user messages-->

            <div class=" yours messages"> 

                <!--avatar-->
                <div class="avatar">
                <% post_user_avatar = room_message.user.avatar%>
                  <% if post_user_avatar.attached? %>
                    <%= image_tag post_user_avatar, size: 50, class: "rounded-circle" %>
                  <% else %>
                    <%= image_tag "default-profile.png", size: 50, class: "rounded-circle" %>
                  <% end %>
              </div>      
                <br>

              <div class="message">
                <p style="font-weight:bold;"> <%= room_message.user.username %></p>
                  <% regex = /(https?:\/\/.*\.(?:png|jpg|jpeg|gif))/i %>
                  <% if room_message.message.match(regex)%>
                    <% img_url = room_message.message.match(regex)%>
                    <% text = room_message.message.gsub(img_url[0], " ")%>
                    <p> <%= text %></p>
                    <%= renderImage(img_url).html_safe %>
                  <% else %>
                    <p class="mb-1">
                      <%= room_message.message %>
                    </p>
                  <% end %>
              </div>

                <div class="text-left">
                  <small>
                  <%= room_message.created_at%>
                  </small>
                </div>
            </div>
          </div>

      <% end %>
  </div>
  <br>
  <%= simple_form_for @room_message, remote: true do |form| %>
    <div class="input-group mb-3">
      <%= form.input :message, as: :string,
                               wrapper: false,
                               label: false,
                               placeholder: "your message here",
                               input_html: {
                                 class: 'chat-input'
                               } %>
      <div class="input-group-append">
        <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
      </div>
    </div>
    <%= form.input :room_id, as: :hidden %>
  <% end %>

  <div class="media-preview"></div>
    <%= link_to new_room_path, class: "btn btn-primary" do %>
      Bored? Try creating a new room
    <% end %>
</div>






<!--each new incoming message will clone this snippet of html. see javascripts/channels/room_channels.js-->
<div class="d-none" data-role="message-template">
  <div class="chat-message-container">

    <div class="yours messages">
      <div class="avatar">
      <img class="rounded-circle" src="" alt="" data-role="user-avatar" style="width: 50px; height: 50px;">

      </div>

      <br>

      <div class="message">
          <p style="font-weight:bold;" class="mb-1" data-role="message-username"></p>
          <p class="mb-1" data-role="message-text"></p>

          <img src="" alt="" data-role="message-media-img">
      </div>

      <div class="text-right">
        <small data-role="message-date"></small>
      </div>
    </div>
  </div>
</div>

<!--6. here we add some data in the room page in order to use it in our Javascript file to subscribe to the appropriate streams each time we visit a room. We add two data attributes, one defining to which channel we want to subscribe "(data-channel-subscribe="room")" and one defining to which room we are "(data-room-id="<%= @room.id %>)"-->

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<br><br>
<div class="container">
  <h2 align="center" class="header-text"> Make your profile stand out </h2>
  <br>

  <div align="center">
    <div class="c-top-container">
      <%= form_for(current_user, url: update_profile_path, method: 'post') do |f| %>
        <div class="c-input">
          <h4><%= f.label :bio %></h4>
            <br>
            <div class="small-field">
            <textarea <%= f.text_field :bio, class:"form-control emoji" %> </textarea>
            </div> 
        </div>
      <br>
          <div class="actions">
            <button class="btn btn-primary"<%= f.submit %>Save</button>
          </div>
      <br>
      <% end %>
    </div>
  </div>
</div>
             

app/views/users/show.html.erb
<div class="container">
<div class="row align-items-center">
<div class="col">
    <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, class: "img-thumbnail" %>
    <% else %>
        <%= image_tag "default-profile.png", class: "img-thumbnail"%>
    <% end %>
    <h1 class="header-text2"><%= @user.first_name %> <%= @user.last_name %></h1>

        <% if @user.id == current_user.id %>
            <%= link_to 'Edit bio', users_path , class: "link-text"%>
        <%end%>

        | <%= link_to "Back", :back, class: "link-text" %>
</div>
<div class="col">
<div class="left-container"
        <h5> About me... </h5>
        <h4><%= current_user.bio %></h4>
</div>
</div>
</div>
</div>